### ISSUE TITLE
Issues when installing mock through buildout

### ISSUE THREAD

**Issue by ZachArani** [testing-cabal/mock#461] opened 2019-05-06 22:17 UTC
Had some issues with mock over the weekend on our Jenkins instance. Pulling the latest version of mock yielded this wonderful message from buildout:

`Installing eggs.
Getting distribution for 'mock'.
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

zip_safe flag not set; analyzing archive contents...
While:
  Installing eggs.
  Getting distribution for 'mock'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
```
Traceback (most recent call last):
  File "/Users/jenkins/jenkinsMaster/workspace/QA/Start Web-Sanity/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/Users/jenkins/jenkinsMaster/workspace/QA/Start Web-Sanity/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/Users/jenkins/jenkinsMaster/workspace/QA/Start Web-Sanity/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/Users/jenkins/cache/nti.qa.buildout-eggs/zc.recipe.egg-2.0.7-py2.7.egg/zc/recipe/egg/egg.py", line 227, in install
    reqs, ws = self.working_set()
  File "/Users/jenkins/cache/nti.qa.buildout-eggs/zc.recipe.egg-2.0.7-py2.7.egg/zc/recipe/egg/egg.py", line 87, in working_set
    allow_unknown_extras=bool_option(buildout_section, 'allow-unknown-extras')
  File "/Users/jenkins/cache/nti.qa.buildout-eggs/zc.recipe.egg-2.0.7-py2.7.egg/zc/recipe/egg/egg.py", line 168, in _working_set
    allow_unknown_extras=allow_unknown_extras)
  File "/Users/jenkins/jenkinsMaster/workspace/QA/Start Web-Sanity/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "/Users/jenkins/jenkinsMaster/workspace/QA/Start Web-Sanity/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/easy_install.py", line 730, in install
    for dist in self._get_dist(req, ws):
  File "/Users/jenkins/jenkinsMaster/workspace/QA/Start Web-Sanity/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/Users/jenkins/jenkinsMaster/workspace/QA/Start Web-Sanity/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/easy_install.py", line 1745, in _move_to_eggs_dir_and_compile
    os.rename(tmp_loc, newloc)
OSError: [Errno 66] Directory not empty
```

If I delete my local buildout cache:

```
Getting distribution for 'mock'.
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

zip_safe flag not set; analyzing archive contents...
While:
  Installing eggs.
  Getting distribution for 'mock'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/jenkins/nti-qa-buildout/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/Users/jenkins/nti-qa-buildout/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/Users/jenkins/nti-qa-buildout/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/Users/jenkins/cache/nti.qa.buildout-eggs/zc.recipe.egg-2.0.7-py2.7.egg/zc/recipe/egg/egg.py", line 227, in install
    reqs, ws = self.working_set()
  File "/Users/jenkins/cache/nti.qa.buildout-eggs/zc.recipe.egg-2.0.7-py2.7.egg/zc/recipe/egg/egg.py", line 87, in working_set
    allow_unknown_extras=bool_option(buildout_section, 'allow-unknown-extras')
  File "/Users/jenkins/cache/nti.qa.buildout-eggs/zc.recipe.egg-2.0.7-py2.7.egg/zc/recipe/egg/egg.py", line 168, in _working_set
    allow_unknown_extras=allow_unknown_extras)
  File "/Users/jenkins/nti-qa-buildout/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "/Users/jenkins/nti-qa-buildout/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/easy_install.py", line 730, in install
    for dist in self._get_dist(req, ws):
  File "/Users/jenkins/nti-qa-buildout/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/Users/jenkins/nti-qa-buildout/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/easy_install.py", line 1771, in _move_to_eggs_dir_and_compile
    assert newdist is not None  # newloc above is missing our dist?!
```

Rolling back to mock 2.00 did fix the issue.

**Comment by cjw296** [comment] 2019-05-07 10:50
It would help to know which distribution buildout is using and what it's actually getting sad about.

**Comment by cjw296** [comment] 2019-05-07 10:57
The wheels don't appear to have any salient structural differences:

```
$ unzip -l mock-2.0.0-py2.py3-none-any.whl 
Archive:  mock-2.0.0-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
      207  07-09-2015 21:35   mock/__init__.py
    83651  04-06-2016 00:42   mock/mock.py
      552  07-31-2015 06:28   mock/tests/support.py
     4431  07-14-2015 02:07   mock/tests/testcallable.py
    50470  03-23-2016 05:59   mock/tests/testmock.py
    56347  03-23-2016 05:54   mock/tests/testpatch.py
      146  07-14-2015 02:07   mock/tests/__init__.py
      623  07-09-2015 07:45   mock/tests/__main__.py
    28697  03-21-2016 00:26   mock/tests/testhelpers.py
      976  07-14-2015 02:07   mock/tests/testsentinel.py
    10587  03-23-2016 05:31   mock/tests/testwith.py
    16379  07-31-2015 06:28   mock/tests/testmagicmethods.py
     1232  04-06-2016 01:38   mock-2.0.0.dist-info/DESCRIPTION.rst
     1818  04-06-2016 01:38   mock-2.0.0.dist-info/metadata.json
       46  04-06-2016 01:38   mock-2.0.0.dist-info/pbr.json
        5  04-06-2016 01:38   mock-2.0.0.dist-info/top_level.txt
      110  04-06-2016 01:38   mock-2.0.0.dist-info/WHEEL
     3163  04-06-2016 01:38   mock-2.0.0.dist-info/METADATA
     1525  04-06-2016 01:38   mock-2.0.0.dist-info/RECORD
---------                     -------
   260965                     19 files

$ unzip -l mock-3.0.4-py2.py3-none-any.whl 
Archive:  mock-3.0.4-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
      113  05-04-2019 13:00   mock/__init__.py
    86948  05-04-2019 13:00   mock/mock.py
     1342  05-04-2019 13:00   mock-3.0.4.dist-info/LICENSE.txt
     3153  05-04-2019 13:00   mock-3.0.4.dist-info/METADATA
      110  05-04-2019 13:00   mock-3.0.4.dist-info/WHEEL
        5  05-04-2019 13:00   mock-3.0.4.dist-info/top_level.txt
      517  05-04-2019 13:00   mock-3.0.4.dist-info/RECORD
---------                     -------
    92188                     7 files
```

**Comment by cjw296** [comment] 2019-05-07 10:57
Neither the tgzs:

```
$ tar tzf mock-2.0.0.tar.gz 
mock-2.0.0/
mock-2.0.0/docs/
mock-2.0.0/docs/conf.py
mock-2.0.0/docs/changelog.txt
mock-2.0.0/docs/index.txt
mock-2.0.0/mock/
mock-2.0.0/mock/tests/
mock-2.0.0/mock/tests/support.py
mock-2.0.0/mock/tests/testcallable.py
mock-2.0.0/mock/tests/testmock.py
mock-2.0.0/mock/tests/testpatch.py
mock-2.0.0/mock/tests/__init__.py
mock-2.0.0/mock/tests/__main__.py
mock-2.0.0/mock/tests/testhelpers.py
mock-2.0.0/mock/tests/testsentinel.py
mock-2.0.0/mock/tests/testwith.py
mock-2.0.0/mock/tests/testmagicmethods.py
mock-2.0.0/mock/__init__.py
mock-2.0.0/mock/mock.py
mock-2.0.0/README.rst
mock-2.0.0/LICENSE.txt
mock-2.0.0/.testr.conf
mock-2.0.0/NEWS
mock-2.0.0/unittest.cfg
mock-2.0.0/requirements.txt
mock-2.0.0/.travis.yml
mock-2.0.0/mock.wpr
mock-2.0.0/tools/
mock-2.0.0/tools/pre-applypatch
mock-2.0.0/tools/applypatch-transform
mock-2.0.0/AUTHORS
mock-2.0.0/extendmock.py
mock-2.0.0/setup.cfg
mock-2.0.0/tox.ini
mock-2.0.0/mock.egg-info/
mock-2.0.0/mock.egg-info/requires.txt
mock-2.0.0/mock.egg-info/not-zip-safe
mock-2.0.0/mock.egg-info/SOURCES.txt
mock-2.0.0/mock.egg-info/dependency_links.txt
mock-2.0.0/mock.egg-info/top_level.txt
mock-2.0.0/mock.egg-info/pbr.json
mock-2.0.0/mock.egg-info/PKG-INFO
mock-2.0.0/ChangeLog
mock-2.0.0/setup.py
mock-2.0.0/PKG-INFO
$ tar tzf mock-3.0.4.tar.gz 
mock-3.0.4/
mock-3.0.4/CHANGELOG.rst
mock-3.0.4/LICENSE.txt
mock-3.0.4/MANIFEST.in
mock-3.0.4/PKG-INFO
mock-3.0.4/README.rst
mock-3.0.4/mock/
mock-3.0.4/mock/__init__.py
mock-3.0.4/mock/mock.py
mock-3.0.4/mock.egg-info/
mock-3.0.4/mock.egg-info/PKG-INFO
mock-3.0.4/mock.egg-info/SOURCES.txt
mock-3.0.4/mock.egg-info/dependency_links.txt
mock-3.0.4/mock.egg-info/requires.txt
mock-3.0.4/mock.egg-info/top_level.txt
mock-3.0.4/setup.cfg
mock-3.0.4/setup.py

```

**Comment by cjw296** [comment] 2019-05-07 10:59
I'm afraid we're going to need more to make progress on this, a minimal reproducer from scratch (buildout.cfg, instructions, etc) would be needed.

**Comment by ZachArani** [comment] 2019-05-07 20:17
I believe I figured out the issue. I (mistakenly) had been using the default MacOS python library (my virtualenv had messed up) and buildout was defaulting to `setuptools 18.5` for the install. Forcing it back to a newer version with a virtualenv (`setuptools 41.0.1`) fixes the issue. I suppose some change from 2.0.0 to 3.0.0 caused older setuptools to fail builds. 

You can observe this by running a `buildout.cfg` installing mock with `setuptools` pinned to `18.5`

**Comment by cjw296** [comment] 2019-05-07 20:58
Okay, I'm not sure we have much interest in supporting old setuptools releases so closing this for now.
However, if you can find an easy fix that would have made it happy, please do feel free to send in a PR!

**Closed by cjw296** 2019-05-07 20:58 UTC

**Comment by reinout** [comment] 2019-06-06 14:12
A colleague had the same "Directory not empty" error today. I added a `print()` statement to buildout and figured out what was happening. The egg directory being created was `UNKOWN-3.0.5.egg/` instead of `mock-3.0.5.egg/`.
The copy action (from a temp dir to the actual buildout `eggs/` dir) failed because there was an `UNKOWN-3.0.5.egg/` already in there from a previous run. Buildout didn't check for the presence of that because it expected a `mock-*`, of course :-)

Totally possible that it was due to an old setuptools. No need to fix it in mock, in any case :-)

**Comment by cjw296** [comment] 2019-06-06 14:18
Sounds like buildout needs to make sure it's using a recent setuptools? I can see all kinds of problems occurring if it's not..

**Comment by reinout** [comment] 2019-06-06 15:41
Well, buildout really likes to have a recent setuptools, but it itself *does* work just fine with older versions. There was a period that setuptools broke buildout once a month with an update, so it wasn't always the best solution to just grab the latest version. And people started pinning setuptools. This was one of those older projects where an older version was used.

The actual problem is that *mock* requires a newer setuptools due to the virtually-empty `setup.py` without the `name="mock"` keyword :-) But you probably don't want to put `setuptools >= xyz` in your install_requires list (and it probably leads to problems if you do so, so I wouldn't do it).

0.01% of the population will have this issue and they are the ones who can find this github issue and thus find the solution :-) So no need to change anything.
