### ISSUE TITLE
assert_called_with scope issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#245] opened 2015-04-21 20:54 UTC
```
What steps will reproduce the problem?
from mock import patch

def foobar():
    data = {
        'first_name': 'Foo',
        'last_name': 'Bar',
        'title': 'Mr'
    }
    print_data(data)
    data['address'] = 'homeless'


def print_data(data):
    print data


@patch('__main__.print_data')
def test_foobar(mock_print_data):
    data = {
        'first_name': 'Foo',
        'last_name': 'Bar',
        'title': 'Mr'
    }
    foobar()
    mock_print_data.assert_called_with(data)

test_foobar()


What is the expected output? What do you see instead?

 Expected output is that the call is made with data and the test passes.

What happens is an assertion error is raised with the data that was appended 
AFTER the call being the culprit:

AssertionError: Expected call: print_data({'first_name': 'Foo', 'last_name': 
'Bar', 'title': 'Mr'})
Actual call: print_data({'first_name': 'Foo', 'last_name': 'Bar', 'address': 
'homeless', 'title': 'Mr'})


What version of the product are you using? On what operating system?
mock - 1.0.1
osx - 10.10.2
python - 2.7.9


Please provide any additional information below.


```

Original issue reported on code.google.com by `ArrantSq...@gmail.com` on 3 Feb 2015 at 9:05

**Comment by rbtcollins** [comment] 2015-07-17 09:32
Ok, so whats happening here is that mock is taking what it was called - the dict - and storing it precisely.

You are then modifying the object it was given, and the comparison fails.

I'm not sure whether fixing this is a good idea. I think it needs more discussion. I'll ping some folk more experienced in mock than I. @kushaldas @berkerpeksag @mfoord 

The reason I think this might be a bad idea is complexity: we'd be calling 'deepcopy' on every call made, and that can be fragile - I've had to monkey patch types into the copy module in the past to fix similar approachs, and I'm leery of the impact on users.

OTOH it is a wart, and not predictable without reading the implementation. So I think at minimum we should document the expected behaviour in the docs, whichever way we fall.

**Comment by mfoord** [comment] 2015-07-20 13:14
> On 17 Jul 2015, at 11:32, rbtcollins <notifications@github.com> wrote:
> 
> Ok, so whats happening here is that mock is taking what it was called - the dict - and storing it precisely.
> 
> You are then modifying the object it was given, and the comparison fails.
> 
> I'm not sure whether fixing this is a good idea. I think it needs more discussion. I'll ping some folk more experienced in mock than I. @kushaldas @berkerpeksag @mfoord
> 
> The reason I think this might be a bad idea is complexity: we'd be calling 'deepcopy' on every call made, and that can be fragile - I've had to monkey patch types into the copy module in the past to fix similar approachs, and I'm leery of the impact on users.
> 
> OTOH it is a wart, and not predictable without reading the implementation. So I think at minimum we should document the expected behaviour in the docs, whichever way we fall.

This is already documented:

https://docs.python.org/3/library/unittest.mock-examples.html#coping-with-mutable-arguments

Michael

> 
> —
> Reply to this email directly or view it on GitHub.
> 


--
http://www.voidspace.org.uk/


May you do good and not evil
May you find forgiveness for yourself and forgive others
May you share freely, never taking more than you give.
-- the sqlite blessing 
http://www.sqlite.org/different.html

**Comment by rbtcollins** [comment] 2015-07-21 16:29
Thanks, closing then.

**Closed by rbtcollins** 2015-07-21 16:29 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
