### ISSUE TITLE
Patches aren't being removed

### ISSUE THREAD

**Issue by jeffhos** [testing-cabal/mock#419] opened 2018-01-08 21:47 UTC
I have a situation where it seems like patches aren't being removed from the objects they patch, even after exiting the `with` block they're applied in.

I have two tests, one of which mocks out a couple methods.  The second needs to use the original, unmocked implementation.  But it seems like the mock isn't being fully removed even though the first test has completed.

Unfortunately, this requires 3 files to reproduce, since it seems to involve import behavior in some way.  Here they are:

Config.py:
```python
def get():
    return "config_value"
```

App.py:
```python
import Config as Config

test_value = Config.get()
util = "blah"
```

tests.py:
```python
from mock import patch

def test1():
    with patch('Config.get') as get:
        get.return_value = "patched_value"
        with patch('App.util'):
            assert True

def test2():
    import App
    assert App.test_value == "config_value"
```

**Expected result:** Both tests pass

**Actual result:** test2 fails:

```
_________________________________________ test2 __________________________________________

    def test2():
        import App
>       assert App.test_value == "config_value"
E       AssertionError: assert 'patched_value' == 'config_value'
E         - patched_value
E         + config_value

tests.py:11: AssertionError
```

**Comment by rbtcollins** [comment] 2018-01-09 12:01
You are importing App during the period that Config.get is mocked; the import-time code in App.py then runs and picks up the mocked value.

You can fix this a number of ways:
- explictly import App in tests.py rather than implicitly through the patch mechanism
- change test2 to not depend on implicit global state
- change App.py to not have sideeffects during importing

Its not a bug a in the patching/mocking system here though; so I'm going to close this ticket. Hope this helped and feel free to follow up with more q's if its unclear.

**Closed by rbtcollins** 2018-01-09 12:01 UTC
