### ISSUE TITLE
Version 1.1.1 installation fails with python 2.7.6

### ISSUE THREAD

**Issue by nils-ohlmeier** [testing-cabal/mock#268] opened 2015-07-10 20:56 UTC
/mock-1.1.1$ python setup.py install
error in setup command: Invalid environment marker: python_version<"3" or python_version>="3.3"

/tmp/mock-1.1.1$ python --version
Python 2.7.6

**Comment by nils-ohlmeier** [comment] 2015-07-10 21:10
So the syntax in these lines:
https://github.com/testing-cabal/mock/blob/master/setup.cfg#L35-L38
https://github.com/testing-cabal/mock/blob/master/requirements.txt#L1
Don't seem to be supported by older python versions. If I remove these lines it seems to work.

**Comment by rbtcollins** [comment] 2015-07-10 21:17
setuptools 17.1 supports this - its not tied into Python version at all. This is a duplicate of #261

**Closed by rbtcollins** 2015-07-10 21:17 UTC
Labels: duplicate
