### ISSUE TITLE
assert_has_calls fails when used with spec class with parameters

### ISSUE THREAD

**Issue by danielnelson** [testing-cabal/mock#352] opened 2016-04-08 01:08 UTC
I am seeing some strange behavior with assert_has_calls.  This test case fails when using mock from python 3.4 or 3.5, or in version 1.1.0 or later.  In python 3.3 or 1.0.1 it passes.

```
class InitArgs:
    def __init__(self, foo):
        pass

    def bar(self):
        pass

class TestSpec(unittest.TestCase):
    def test_spec_args(self):
        mock = Mock(spec=InitArgs)
        mock.bar()
        mock.assert_has_calls([call.bar()])
```

Here is the error:

```
Traceback (most recent call last):
  File "payment-service/test_spec.py", line 23, in test_spec_args
    mock.assert_has_calls([call.bar()])
  File "lib/python3.4/site-packages/mock/mock.py", line 962, in assert_has_calls
    ), cause)
  File "<string>", line 2, in raise_from
AssertionError: Calls not found.
Expected: [call.bar()]
Actual: [call.bar()]
```

If you remove the argument from the spec classes `__init__` then the test passes.

**Comment by rbtcollins** [comment] 2016-04-08 02:28
Please file a ticket on cPython itself then - https://bugs.python.org/

**Comment by xsleonard** [comment] 2016-11-28 19:32
>If you remove the argument from the spec classes __init__ then the test passes.

This is because it is trying to `bind()` the args list of `call.bar()`, which is empty, to the function signature of `InitArgs.__init__` and not to `InitArgs.bar`.  By removing the args from `__init__`, both `__init__` and `bar` have the same signature, `(self)`.  When the signatures do not match, the raised `TypeError` is caught as returned.  The reason it fails to match is that it is comparing `call.bar()` to a `TypeError: 'foo' parameter lacking default value` internally.

https://github.com/testing-cabal/mock/blob/286792b2cd5b5baa8338260538ed207391280e34/mock/mock.py#L868-L888

Perhaps it should fall back and `return _call` instead for `assert_has_calls` since it accepts a `mock.call` directly which may refer to a method on the class that is mocked, rather than a directly mocked method, thus the sig binding against a class spec's `__init__` will fail.

The other problem is here,
https://github.com/testing-cabal/mock/blob/286792b2cd5b5baa8338260538ed207391280e34/mock/mock.py#L962
`expected` is a list, so `cause` is always `None`, which is why the error message is unclear.

This doesn't look like an upstream issue.

**Comment by tirkarthi** [comment] 2019-04-30 07:38
I think there are multiple variants of call_matcher breaking with spec reported upstream. The problem is with self being part of the function used to validate the signature and in call_matcher self is not passed. I am not sure if this the same as one reported here. It would be great to have this fixed and also see different approaches at https://bugs.python.org/issue26752

Related upstream bugs related to call_matcher and spec

https://bugs.python.org/issue26752
https://bugs.python.org/issue27715
https://bugs.python.org/issue25312

**Comment by cjw296** [comment] 2019-04-30 07:42
Okay, let's close this issue and when they're fixed upstream we can get them into the backport.

**Closed by cjw296** 2019-04-30 07:42 UTC
Labels: incomplete
