### ISSUE TITLE
create_autospec doesn't override instance methods on class object

### ISSUE THREAD

**Issue by yangchenyun** [testing-cabal/mock#351] opened 2016-04-06 22:17 UTC
Give the following code:

``` py
class Foo(object):
    def a(self):
        print 'a'
```

`create_autospec` doesn't work for overriding instance methods defined on class. It doesn't work to override the method on the class object itself.

``` py
MockedFoo = mock.create_autospec(Foo, **{'a.return_value': 'mock'})
MockedFoo.a()  # 'mock', this is expected
foo = MockedFoo()
foo.a()  #  <MagicMock name='mock.a()' id='24082064'>
```

It doesn't work if trying to override the method on the mocked instance as well.

``` py
mockedFooInstance = mock.create_autospec(Foo, instance=True, **{'a.return_value': 'mock'})
mockedFooInstance.a() = <MagicMock name='mock.a()' id='24109584'>
```

**Comment by rbtcollins** [comment] 2016-04-06 23:31
Dupe of #241 ?

**Comment by cjw296** [comment] 2018-11-29 08:29
@rbtcollins - let's hope so ;-)

**Closed by cjw296** 2018-11-29 08:29 UTC
